# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #General configuration
  config.ssh.username = "admin"
  config.ssh.private_key_path = "../packer/acit_4640_base/acit_admin_id_rsa"
  
  #Specifiy the base box here
  config.vm.box = "../packer/centos_base.box"

  #VM specific configuration
  #see : https://www.vagrantup.com/docs/multi-machine/
  config.vm.define "wp" do |wp|
    wp.vm.hostname = "wp"
    wp.vm.network "forwarded_port", guest: 443, host: 50443
    wp.vm.network "forwarded_port", guest: 80, host: 50080
    wp.vm.network "forwarded_port", guest: 22, host: 50022
    
    #other machine configuration items go here
    wp.vm.provider "virtualbox" do |vb|
      vb.name = "wp"
      vb.linked_clone = true
      vb.customize ["modifyvm", :id, "--memory", "1280"]
      #all other provider configuration items go here
    end
    wp.vm.provision :ansible do |ansible|
      #playbook path is relative to the Vagrantfile
      ansible.playbook = "provisioning/wordpress.yml"
      #ansible.inventory_path = "provisioning/hosts"
    end
  end

  #General provisioning Configuration 
  
end