---
- hosts: wp
  become: yes
  tasks:

      #EPEL Repo

    - name: Add repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

    - include_role:
        name: nginx  

    - include_role:
        name: php

    - include_role:
        name: mariadb

    - include_role: 
        name: wordpress
      vars:
        mariadb_priv_user: root
        mariadb_priv_user_passwd: password
        wordpress_db: wordpress
        wordpress_db_user: wordpress_user
        wordpress_db_user_passwd: P@ssw0rd
      



